Module 1 Capstone Project
see-why/ComicCon pull request #2
Opened 2021-09-10 16:41 UTC by see-why

2021-09-10 19:29 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @see-why 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
-  Git/GitHub flow best practices have been followed.:heavy_check_mark:
- The live link demo is working properly:heavy_check_mark:

Changes required :writing_hand: 
 
    - Please check the comment under the review.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-10 19:29 UTC, Emmyn5600 commented on index.html
>                  <hr>
#### Mobile Size
It contains an hamburger menu on the left side.

- [ ] The hamburger button on the mobile section should be clickable and display the menu.

- [ ] I suggest to change the font-size for our first heading to look more clear on the mobile section 

![cpp14](https://user-images.githubusercontent.com/55635977/132903302-976fafa9-4467-4588-8f23-eae1307b8637.png)

-  I suggest to change the font-size for our first heading to look more clear on the mobile section 
![cpp15](https://user-images.githubusercontent.com/55635977/132904894-1753485a-d5a8-44b0-98a7-50a5edc78d6b.png)

2021-09-10 19:29 UTC, Emmyn5600 commented on scripts/export.js
> +}
- [ ] Great implementation here to use Js file to keep the image and description for the featured speakers however, let us add some decoration to the image.

-----------------------------------------------Yours---------------------------------------

![cpp16](https://user-images.githubusercontent.com/55635977/132905452-2c063ed9-2ef4-42fc-8183-91dfe5d04a1f.png)

------------------------------------------Original---------------------------------------------

![cpp17](https://user-images.githubusercontent.com/55635977/132905457-637feea9-5c0b-49b8-954c-9328cb37a0e9.png)

2021-09-11 05:06 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑🛠**
Hello @see-why 👋🏽
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._👀👇🏽
- As the previous code reviewer said, the project contains 2 pages; the `home page` and the `About page` but you are missing the About page. Please fix that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 08:21 UTC, Georjane approved these changes
## Status: PR Approved 💯 🥇 
#### Hello @see-why. 

Your project is complete!  You have met all requirements for this project. It is a thumbs up for me. 👍🏽 You can go ahead and merge this PR. 
Congratulations! 🎉 👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] You can add the following section in your Readme file to help those that are interested in your project to easily get it set up locally
```
## Getting Started
To get a local copy of the repository please run the following commands on your terminal:
$ git clone https://github.com/...
$ cd ...
$ git checkout ...
$ Open index.html in your browser or with a live server
```

_Good luck with your next project and Happy coding!_ 💻

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-11 08:27 UTC, see-why commented
> ## Status: PR Approved 💯 🥇
> #### Hello @see-why.
> Your project is complete! You have met all requirements for this project. It is a thumbs up for me. 👍🏽 You can go ahead and merge this PR.
> Congratulations! 🎉 👏👏
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> * [x]  You can add the following section in your Readme file to help those that are interested in your project to easily get it set up locally
> 
> ```
> ## Getting Started
> To get a local copy of the repository please run the following commands on your terminal:
> $ git clone https://github.com/...
> $ cd ...
> $ git checkout ...
> $ Open index.html in your browser or with a live server
> ```
> 
> _Good luck with your next project and Happy coding!_ 💻
> 
> Cheers and Happy coding! 💻
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝
> 
> _Code Reviewer **[Jane](https://witahgeorjane.tech/)**_
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

thanks a lot.
I have added it as you suggested.

2021-09-11 08:29 UTC, merged